export const defaultToothbrushParams = {
  handleLength: 195, // adult standard in mm
  handleWidth: 15,
  handleThickness: 6,
  indentLength: 28,
  indentDepth: 4,
  headLength: 29,
  headWidth: 12,
  headThickness: 8,
  neckLength: 15,
  bristleRows: 4,
  bristleColumns: 10,
  bristleHeight: 11,
  bristleRadius: 1.4,
  bristleSpacingRatio: 0.65,
};

export const sliderGroups = [
  {
    title: "Handle",
    sliders: [
      {
        key: "handleLength",
        label: "Handle Length",
        min: 140,
        max: 210,
        step: 1,
        unit: "mm",
      },
      {
        key: "handleWidth",
        label: "Handle Width",
        min: 10,
        max: 20,
        step: 0.5,
        unit: "mm",
      },
      {
        key: "handleThickness",
        label: "Handle Thickness",
        min: 4,
        max: 12,
        step: 0.2,
        unit: "mm",
      },
      {
        key: "indentLength",
        label: "Indent Length",
        min: 10,
        max: 45,
        step: 1,
        unit: "mm",
      },
      {
        key: "indentDepth",
        label: "Indent Depth",
        min: 1,
        max: 6,
        step: 0.2,
        unit: "mm",
      },
    ],
  },
  {
    title: "Head",
    sliders: [
      {
        key: "headLength",
        label: "Head Length",
        min: 20,
        max: 35,
        step: 1,
        unit: "mm",
      },
      {
        key: "headWidth",
        label: "Head Width",
        min: 10,
        max: 18,
        step: 0.5,
        unit: "mm",
      },
      {
        key: "headThickness",
        label: "Head Thickness",
        min: 6,
        max: 12,
        step: 0.5,
        unit: "mm",
      },
      {
        key: "neckLength",
        label: "Neck Length",
        min: 8,
        max: 25,
        step: 1,
        unit: "mm",
      },
    ],
  },
  {
    title: "Bristles",
    sliders: [
      {
        key: "bristleRows",
        label: "Bristle Rows",
        min: 2,
        max: 8,
        step: 1,
      },
      {
        key: "bristleColumns",
        label: "Bristle Columns",
        min: 4,
        max: 16,
        step: 1,
      },
      {
        key: "bristleHeight",
        label: "Bristle Height",
        min: 6,
        max: 14,
        step: 0.5,
        unit: "mm",
      },
      {
        key: "bristleRadius",
        label: "Bristle Radius",
        min: 0.6,
        max: 2.6,
        step: 0.1,
        unit: "mm",
      },
      {
        key: "bristleSpacingRatio",
        label: "Spacing Ratio",
        min: 0.4,
        max: 0.9,
        step: 0.05,
      },
    ],
  },
];
